volumes:
  pgdata:
services:
  webapp:
    build: .
    ports:
      - 5080:5080
    environment:
      MONGODB_URL: mongodb://dbservice:27017/todo
  dbservice:
    image: postgres
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql