@startuml
actor player
autonumber

player -> frontend: Start game
frontend -> backend: Start new game
frontend <- backend: [Game ID]
player <- frontend: Prompt for guess
player -> frontend: Guess
frontend -> backend: Submit guess [Game ID]
note over backend
  The guess is compared
  with the correct word
  from step 3
end note
frontend <- backend: Respond whether correct

group If incorrect
note over player, backend
Repeat 4-7
end note
end

group If correct
player <- frontend: Show won screen
player -> frontend: Enter name
frontend -> backend: Submit name [Game ID]
player <- frontend: Show end screen
end

@enduml
