@startuml

actor User

package frontend {
  component Browser
  component "Frontend JS" as js
  component CSS

  Browser <--> js
  Browser <-- CSS
}

package backend {
  component Express
  component Route
  component "Logical Unit" as unit
  component CMSAdapter
  component IMDBAdapter

  Express --> Route
  Route --> unit
  unit --> CMSAdapter
  unit --> IMDBAdapter
}

cloud "CMS API" as cms
cloud "IMDB API" as imdb

User -> Browser
js --> Express
CMSAdapter --> cms
IMDBAdapter --> imdb

@enduml
