@startuml
skinparam componentStyle rectangle

' Vårt system ur OOP-perspektiv
' - Vilka roller finns?
' - Vilka meddelanden behöver de kunna hantera?
' - Vilka typer av objekt spelar de här rollerna?

component APIAdapter
component FormValidator
component UserInterface
component Challenge
component ChallengeList
component Filter
component FilterCollection
component RatingFilter
component StringFilter
component LabelFilter

UserInterface --> FormValidator: Is input valid?
UserInterface --> ChallengeList: Show yourself (render DOM)
ChallengeList --> APIAdapter: Load challenges
ChallengeList --> Filter: Does this challenge match?
ChallengeList --> Challenge: Show yourself! (render DOM)

Filter <-- RatingFilter: is
Filter <-- StringFilter: is
Filter <-- LabelFilter: is
Filter <-- FilterCollection: is

@enduml