@startuml
actor player
autonumber

player -> frontend: Start game
frontend -> backend: Request random word
frontend <- backend: Respond with random word
player <- frontend: Prompt for guess
player -> frontend: Guess
note over frontend
  The guess is compared
  with the correct word
  from step 3
end note

group If incorrect
player <- frontend: Prompt for another guess
player -> frontend: Guess (repeat from 5)
end

group If correct
player <- frontend: Show won screen
player -> frontend: Enter name
frontend -> backend: Submit highscore (name, time etc)
player <- frontend: Show end screen
end

@enduml
