import ClickCounter from "@/components/ClickCounter";
import "./global.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
        <ClickCounter/>
      </body>
    </html>
  )
}
